### ISSUE TITLE
How to load the zephyr firmware?

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-tensorflow-lite-demo#13]
Maybe I missed it -- I don't see where it is described how to load the zephyr.bin firmware onto the Arty board.   That step is pretty difficult for a beginner to figure out.

**Comment by tcal-x** [comment]
@kgugala , it seems I can't assign this to someone.   Can you assign it to the right person?
Thanks, 
Tcal

**Comment by tcal-x** [comment]
@kamilrakoczy @kgugala, in case it's useful, this is the command I used to load the firmware and run the demo on the board:

```
lxterm /dev/ttyUSB0 --kernel ../tensorflow/tensorflow/lite/micro/tools/make/gen/zephyr_vexriscv_x86_64/magic_wand/CMake/zephyr/zephyr.bin
```
..although, can we assume that "lxterm" has been installed?

**Comment by tcal-x** [comment]
I see that in litex-buildenv/targets/arty/Makefile.mk, there is a target for loading firmware, using "flterm", which is available at litex-vexriscv-tensorflow-lite-demo/litex-buildenv/build/conda/bin/flterm.

But I'm not sure if you could use that; you'd need to figure out how to set FIRMWARE_FILEBASE correctly for the TFLite zephyr.bin file.   It's probably easier just to put the "flterm ..." command directly in the demo instructions.

**Comment by mateusz-holenko** [comment]
@tcal-x - do you think that what I propose in https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo/commit/49546b8a2a0a23675684061be4a32dc08aa6a097 is enough?

**Comment by mateusz-holenko** [comment]
The `flterm` command example is now included in Readme on master.
