### ISSUE TITLE
Missing sudo

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-tensorflow-lite-demo#15]
Minor point, but you need to add `sudo` to this line:

```
./zephyr-sdk-0.11.2-setup.run -- -d /opt/zephyr-sdk
```

Of course, when you try without sudo, Linux will tell you that you should use sudo.  So I don't think anyone will get stuck here.

**Comment by mateusz-holenko** [comment]
Probably not stuck, but it would be definiately easier for the user if the `sudo` command is already there in the instruciton.

This is now fixed in https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo/tree/readme_fixes and will be merged soon to master.
