### ISSUE TITLE
"git checkout -b tf_demo" should be in the main cut-and-paste commands, not in the text

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-tensorflow-lite-demo#16]
Since in my experience this **always** needs to be done, it should be in the "block" text of commands to run, not a note in the text.   I missed it the first time through (actually both times I went through the demo), and Daniel the intern also just missed it.

The error "fatal: ref HEAD is not a symbolic ref" is not right at the bottom of the messages, so it's easy to miss.

**Comment by mateusz-holenko** [comment]
That's a very good point. I moved the command to the instructions block in https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo/tree/readme_fixes and will merge it to master soon.
