### ISSUE TITLE
Missing Sensors.ADXL345 when running demo from Tensorflow.org blog instructions

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-tensorflow-lite-demo#19]
Symptom:

```
Renode, version 1.9.0.27103 (169a3c85-202003101317)

(monitor) i $CWD/litex-vexriscv-tflite.resc
There was an error executing command 'machine LoadPlatformDescription /home/tcal/antmicro/litex-vexriscv-tensorflow-lite-demo/renode/litex-vexriscv-tflite.repl'
Error E04: Could not resolve type: 'Sensors.ADXL345'.
At /home/tcal/antmicro/litex-vexriscv-tensorflow-lite-demo/renode/litex-vexriscv-tflite.repl:28:10:
adxl345: Sensors.ADXL345 @ i2c 0x1D
         ^^^^^^^^^^^^^^^^
(machine-0)
```

I was following the instructions at
https://github.com/renode/renode/blob/master/README.rst#installation  
I installed the package 
https://github.com/renode/renode/releases/download/v1.9.0/renode_1.9.0_amd64.deb
from this page:
https://github.com/renode/renode/releases/tag/v1.9.0

I'm at commit 4cf9bde3f0b474e4477aa7523fa9c799557d720e of  https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo.

**Comment by pgielda** [comment]
As far as I remember ADXL345 model was added after the last release.
You have to use nightly version, compile from sources, or wait for a new release which will be out soon.

**Comment by tcal-x** [comment]
Yes, I know how to work around the issue; I was just pointing out that currently the demo is broken from the point of view of some beginner trying to follow the instructions.

**Comment by tcal-x** [comment]
I see this is a duplicate of issue #17...hopefully the new release will be available soon.
