### ISSUE TITLE
CMake 3.13.1 is required for demo but not available on Ubuntu 18.04 through normal channels

### ISSUE THREAD

**Issue by tcal-x** [antmicro/litex-vexriscv-tensorflow-lite-demo#20]
I'm following instructions at https://blog.tensorflow.org/2020/06/running-and-testing-tf-lite-on-microcontrollers.html .

When building the tensorflow binary, I encounter the following error on Ubuntu 18.04:
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.13.1 or higher is required.  You are running version 3.10.2
```
I believe the CMakeLists.txt file referred to is
```
tensorflow/tensorflow/lite/micro/tools/make/gen/zephyr_vexriscv_x86_64/prj/magic_wand/cmake/CMakeLists.txt
```
Are there non-standard channels where I can get 3.13.1?   If so, it should be added to the demo instructions.
Or, can the build process be made compatible with CMake 3.10?

```
$ apt-cache policy cmake
cmake:
  Installed: 3.10.2-1ubuntu2.18.04.1
  Candidate: 3.10.2-1ubuntu2.18.04.1
  Version table:
 *** 3.10.2-1ubuntu2.18.04.1 500
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.10.2-1ubuntu2 500
        500 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

I can't tell if this is a TensorFlow issue, a Zephyr issue, or other.

@mgielda , any comment on the best fix here?

**Comment by mateusz-holenko** [comment]
@tcal-x thanks for reporting the issue!

This is true that the default version of `cmake` provided by Ubuntu is too old for Zephyr. That's why we instruct to install the newer version using pip3 in [the Readme file](https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo/blame/4cf9bde3f0b474e4477aa7523fa9c799557d720e/README.md#L29-L30).

Hope this resolves the problem.

**Comment by tcal-x** [comment]
This is fixed in README, although maybe not in the blog postings.
